spring.application.name=linknix

spring.datasource.url=jdbc:postgresql://localhost:5432/linknix
spring.datasource.username=postgres
spring.datasource.password=ALTERE_AQUI_SUA_SENHA
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
